services:
  keycloak:
    container_name: smart-keycloak  # If you change this, you must also change it in deploy.sh
    environment:
      - KC_HOSTNAME_STRICT_HTTPS=${KC_HOSTNAME_STRICT_HTTPS}
      - KC_HOSTNAME_URL=${KEYCLOAK_HOSTNAME_URL}
      - KC_HOSTNAME_ADMIN_URL=${KEYCLOAK_HOSTNAME_ADMIN_URL}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_TARGET_REALM=${KEYCLOAK_TARGET_REALM}
      - KEYCLOAK_TERRAFORM_CLIENT_ID=${KEYCLOAK_TERRAFORM_CLIENT_ID}
      - KEYCLOAK_TERRAFORM_CLIENT_SECRET=${KEYCLOAK_TERRAFORM_CLIENT_SECRET}
      - KEYCLOAK_TARGET_REALM_DISPLAY_NAME=${KEYCLOAK_TARGET_REALM_DISPLAY_NAME}
    build:
      #context: https://github.com/zedwerks/keycloak-smart-fhir.git#main
      # above only when your project is in a different repo than this one.
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command:
      - start-dev
      - --log-level=INFO
      - --import-realm


