version: "3.8"
services:
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_TARGET_REALM=${KEYCLOAK_TARGET_REALM}
      - KEYCLOAK_TERRAFORM_CLIENT_ID=${KEYCLOAK_TERRAFORM_CLIENT_ID}
    build:
      #context: https://github.com/zedwerks/keycloak-smart-fhir.git#main
      context: ../
      dockerfile: Dockerfile
      args:
        target_realm: ${KEYCLOAK_TARGET_REALM}
        target_realm_display_name: ${KEYCLOAK_TARGET_REALM_DISPLAY_NAME}
        terraform_client_id: ${KEYCLOAK_TERRAFORM_CLIENT_ID}
        terraform_client_secret: ${KEYCLOAK_TERRAFORM_CLIENT_SECRET}
    ports:
      - 8080:8080
    command:
      - start-dev
      - --log-level=INFO
      - --import-realm
      - --features=token-exchange,authorization,admin-fine-grained-authz
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
