services:
  keycloak:
    container_name: smart-keycloak  # If you change this, you must also change it in deploy.sh
    environment:
      - KC_HOSTNAME_STRICT_HTTPS=${KC_HOSTNAME_STRICT_HTTPS}
      - KC_HOSTNAME_URL=${KEYCLOAK_HOSTNAME_URL}
      - KC_HOSTNAME_ADMIN_URL=${KEYCLOAK_HOSTNAME_ADMIN_URL}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_TARGET_REALM=${KEYCLOAK_TARGET_REALM}
      - KEYCLOAK_TERRAFORM_CLIENT_ID=${KEYCLOAK_TERRAFORM_CLIENT_ID}
      - KEYCLOAK_TERRAFORM_CLIENT_SECRET=${KEYCLOAK_TERRAFORM_CLIENT_SECRET}
      - KEYCLOAK_TARGET_REALM_DISPLAY_NAME=${KEYCLOAK_TARGET_REALM_DISPLAY_NAME}
    build:
      #context: https://github.com/zedwerks/keycloak-smart-fhir.git#main
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command:
      - start-dev
      - --log-level=INFO
      - --import-realm
      - --features-disabled=account3,impersonation
      - --features=authorization
  smartcontext:
    # This an example context service. It consumes any JSON and returns it as a response.
    # The default uses the FHIRcast JSON as shown in the FHIRcast examles folder.
    container_name: smart-context
    image: smartcontext
    build:
      context: https://github.com/zedwerks/smart-context.git#main
    ports:
      - "8088:8088"
    environment:
    - ISSUER=${ISSUER}
    - JWKS_URI=${JWKS_URI}
    - SCOPES=${SCOPES}
    - API_KEY=${API_KEY}

