name: Publish and Deploy to DigitalOcean

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
env:
    REGISTRY_URL: "https://registry.digitalocean.com/zedwerks"
    REGISTRY: registry.digitalocean.com/zedwerks
    IMAGE_NAME: keycloak-smart-fhir
    DROPLET_NAME: smart-kc
    DROPLET_REGION: tor1
    DROPLET_SIZE: s-1vcpu-1gb
    SSH_KEY_ID: "NONE"
    SSH_KEY_FINGERPRINT: "NONE"
    DROPLET_IP: "blank"
    droplet_exists: "false"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived token
        run: doctl registry login --expiry-seconds 600

      - name: Extract short SHA for tagging image
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::8}"

      - name: Docker login
        run: docker login ${{ env.REGISTRY }}

      - name: Build Docker image
        run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}

      - name: Push Docker image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract short SHA referencing the image tag
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::8}"

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

      - name: Check if droplet exists
        id: check_droplet
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
        run: |
          if doctl compute droplet list --no-header --format Name | grep -q "^$DROPLET_NAME$"; then
            echo "Droplet already exists."
            echo "droplet_exists=true" >> $GITHUB_ENV
          else
            echo "Droplet does not exist."
            echo "droplet_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Droplet if needed
        if: env.droplet_exists == 'false'
        id: create_droplet
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
          DROPLET_REGION: ${{ env.DROPLET_REGION }}
          DROPLET_SIZE: ${{ env.DROPLET_SIZE }}
          DROPLET_KEY_FINGERPRINT: ${{ secrets.DO_SSH_KEY_FINGERPRINT }}
        run: |
          doctl compute droplet create $DROPLET_NAME \
            --verbose \
            --region $DROPLET_REGION \
            --size $DROPLET_SIZE \
            --image docker-20-04 \
            --ssh-keys $DROPLET_KEY_FINGERPRINT \
            --wait \
            --format ID,PublicIPv4 \
            --no-header \
            --output json > droplet.json

      - name: Get Droplet IP
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
        run: |
          DROPLET_IP=$(doctl compute droplet list --no-header --format Name,PublicIPv4 | grep "$DROPLET_NAME" | awk '{print $2}')
          echo "DROPLET_IP=${DROPLET_IP}" >> $GITHUB_ENV
      
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        env:
          DROPLET_IP: ${{ env.DROPLET_IP }}
          DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          REGISTRY_URL: ${{ env.REGISTRY_URL }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_SHA: ${{ steps.vars.outputs.short_sha }}
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Docker
            apt-get update
            apt-get install -y docker-ce docker-ce-cli containerd.io
            docker --version

            # doctl login
            #doctl registry login -t $DIGITALOCEAN_ACCESS_TOKEN $REGISTRY
            # Login to Digital Ocean Container Registry
            docker login -t $DIGITALOCEAN_ACCESS_TOKEN $REGISTRY_URL 

            # Pull the Docker Image 
            docker pull $REGISTRY/$IMAGE_NAME:$GITHUB_SHA

            # Stop all running Docker Containers
            docker kill $(docker ps -q)

            # Free up space
            docker system prune -a

            # Run a new container from a new image
            docker run -d --name $IMAGE_NAME -p 80:8080 $REGISTRY/$IMAGE_NAME:$GITHUB_SHA



   