name: Deploy Keycloak
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        default: "latest"
      target_environment:
        description: "Target Environment"
        required: true
        default: "demo"
env:
  REGISTRY_URL: "https://registry.digitalocean.com/zedwerks"
  REGISTRY: registry.digitalocean.com/zedwerks
  IMAGE_NAME: keycloak-smart-fhir
  CONTAINER_NAME: keycloak-smart-fhir
  DROPLET_NAME: smart-on-fhir
  DROPLET_REGION: tor1
  DROPLET_SIZE: s-1vcpu-1gb
  DROPLET_IP: "blank"
  droplet_exists: "false"
  IMAGE_TAG: ${{ inputs.image_tag }}
  KEYCLOAK_HOSTNAME_URL: 'http://localhost:8080'
  KEYCLOAK_TARGET_REALM: 'smart'
  KEYCLOAK_TERRAFORM_CLIENT_ID: 'terraform'

jobs:
   droplet:
    name: Create Droplet, if not exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

      - name: Check if droplet exists
        id: check_droplet
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
        run: |
          if doctl compute droplet list --no-header --format Name | grep -q "^$DROPLET_NAME$"; then
            echo "Droplet already exists."
            echo "droplet_exists=true" >> $GITHUB_ENV
          else
            echo "Droplet does not exist."
            echo "droplet_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Droplet if needed
        if: env.droplet_exists == 'false'
        id: create_droplet
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
          DROPLET_REGION: ${{ env.DROPLET_REGION }}
          DROPLET_SIZE: ${{ env.DROPLET_SIZE }}
        run: |
          doctl compute droplet create $DROPLET_NAME \
            --verbose \
            --region $DROPLET_REGION \
            --size $DROPLET_SIZE \
            --image docker-20-04 \
            --ssh-keys $DO_S
   deploy:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: droplet
    environment: ${{ inputs.target_environment }}
    
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get Droplet IP
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
        run: |
          DROPLET_IP=$(doctl compute droplet list --no-header --format Name,PublicIPv4 | grep "$DROPLET_NAME" | awk '{print $2}')
          echo "DROPLET_IP=${DROPLET_IP}" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Set environment
        run: echo "Deploying to ${{ github.events.inputs.environment }} environment"

      - name: Log in to DigitalOcean Container Registry with short-lived token
        run: doctl registry login --expiry-seconds 600

      - name: Docker registry login
        run: docker login ${{ env.REGISTRY }}

      - name: Install Certbot on Droplet
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Install Certbot for SSL certificate generation (if using Let's Encrypt)
            if ! command -v certbot &> /dev/null
            then
              apt-get update
              apt-get install -y certbot
            fi

      - name: Create Certificate for HTTPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          envs: DOMAIN_NAME, EMAIL
          script: |
            # poke the firewall of the droplet
            ufw allow 80
            ufw allow 443

            # Set the domain name
            DOMAIN_NAME=kc.zedwerks.com

            # Set the email address
            EMAIL=brad@zedwerks.com

            # Generate SSL certificate using Certbot
            certbot certonly --standalone -d $DOMAIN_NAME --non-interactive --agree-tos -m $EMAIL
            #certbot renew --dry-run

      - name: Deploy Keycloak with HTTPS
        uses: appleboy/ssh-action@v1.1.0
        env:
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          KEYCLOAK_HOSTNAME_URL: ${{ env.KEYCLOAK_HOSTNAME_URL }}
          KEYCLOAK_TARGET_REALM: ${{ env.KEYCLOAK_TARGET_REALM }}
          KEYCLOAK_TERRAFORM_CLIENT_ID: ${{ env.KEYCLOAK_TERRAFORM_CLIENT_ID }}
          KEYCLOAK_TERRAFORM_CLIENT_SECRET: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}
          DOCKER_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          DOCKER_REGISTRY: ${{ env.REGISTRY }}
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          envs: DOCKER_IMAGE, DOCKER_REGISTRY, CONTAINER_NAME, KEYCLOAK_ADMIN_PASSWORD, KEYCLOAK_HOSTNAME_URL, KEYCLOAK_TARGET_REALM, KEYCLOAK_TERRAFORM_CLIENT_ID, KEYCLOAK_TERRAFORM_CLIENT_SECRET
          script: | 
            echo "DOCKER_IMAGE: $DOCKER_IMAGE"
            echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"
            echo "CONTAINER_NAME: $CONTAINER_NAME"
            echo "KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD"
            echo "KEYCLOAK_HOSTNAME_URL: $KEYCLOAK_HOSTNAME_URL"
            echo "KEYCLOAK_TARGET_REALM: $KEYCLOAK_TARGET_REALM"
            echo "KEYCLOAK_TERRAFORM_CLIENT_ID: $KEYCLOAK_TERRAFORM_CLIENT_ID"
            echo "KEYCLOAK_TERRAFORM_CLIENT_SECRET: $KEYCLOAK_TERRAFORM_CLIENT_SECRET"
            # Remove all older images not in use, etc.
            echo y | docker system prune -a

            # Login to the registry
            docker login $DOCKER_REGISTRY

            # Pull the latest Docker image
            docker pull $DOCKER_IMAGE

            # Stop and remove any existing Keycloak containers
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            # Run Keycloak with HTTPS configured
            echo "Starting Keycloak with HTTPS..."
            docker run -d --name $CONTAINER_NAME \
              -p 80:8080 \
              -p 443:8443 \
              -v /etc/letsencrypt/live/$DOMAIN_NAME:/etc/x509/https \
              -v /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem:/etc/x509/https/fullchain.pem:ro \
              -v /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem:/etc/x509/https/privkey.pem:ro \
              -e KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/fullchain.pem \
              -e KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/privkey.pem \
              -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
              -e KC_BOOTSTRAP_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD \
              -e KEYCLOAK_ADMIN=admin \
              -e KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD \
              -e KC_HOSTNAME_STRICT_HTTPS=true \
              -e KC_HOSTNAME_URL=$KEYCLOAK_HOSTNAME_URL \
              -e KEYCLOAK_TARGET_REALM=$KEYCLOAK_TARGET_REALM \
              -e KEYCLOAK_TERRAFORM_CLIENT_ID=$KEYCLOAK_TERRAFORM_CLIENT_ID \
              -e KEYCLOAK_TERRAFORM_CLIENT_SECRET=$KEYCLOAK_TERRAFORM_CLIENT_SECRET \
              $DOCKER_IMAGE start-dev \
                  --https-key-store-file=/etc/x509/https/privkey.pem \
                  --https-key-store-password=password \
                  --import-realm \
                  --features-disabled=account3,impersonation \
                  --health-enabled=true

      - name: Wait for Keycloak to start
        uses: appleboy/ssh-action@v1.1.0
        env:
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          envs: CONTAINER_NAME
          script: |
            echo "Waiting for Keycloak to start..."
            for i in {1..30 }; do
              if docker exec -t $CONTAINER_NAME /bin/bash -c "curl -s -k -I http://localhost:80/realms/master/.well-known/openid-configuration" > /dev/null; then
                echo "Keycloak is up and running!"
                break
              else
                echo "Keycloak is not up yet. Waiting..."
                sleep 5 
              fi
            done
            docker ps -a
        timeout-minutes: 5

      - name: Add realm-admin for terraform client
        uses: appleboy/ssh-action@v1.1.0
        env:
          KEYCLOAK_TERRAFORM_CLIENT_ID: ${{ env.KEYCLOAK_TERRAFORM_CLIENT_ID }}
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
          KEYCLOAK_TARGET_REALM: ${{ env.KEYCLOAK_TARGET_REALM }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
        with:
            host: ${{ env.DROPLET_IP }}
            username: root
            key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
            envs: KEYCLOAK_ADMIN, \
              KEYCLOAK_ADMIN_PASSWORD, \
              KEYCLOAK_TARGET_REALM, \
              CONTAINER_NAME
            script: |
             echo "Setting up realm-admin for the terraform client..."
             docker exec -t \
              -e KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN \
              -e KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD \
              -e KEYCLOAK_TARGET_REALM=$KEYCLOAK_TARGET_REALM \
              -w /opt/keycloak/bin \
              $CONTAINER_NAME /bin/bash -c ./terraform-realm-admin.sh
