name: Build and Test

on:
  workflow_run:
    workflows: ["CodeQL", "tfsec"]
    types:
      - completed
  workflow_dispatch:

env:
    IMAGE_NAME: keycloak-smart-fhir

jobs:
 # test:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build .


