name: Java Static Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Temurin OpenJDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install SpotBugs
        run: |
          curl -sL https://github.com/spotbugs/spotbugs/releases/download/4.2.3/spotbugs-4.2.3.tgz | tar -xz
          ./spotbugs-4.2.3/bin/spotbugs -textui -emacs -effort:max -high -low src/