name: "Terraform Apply"

on:
  workflow_dispatch: # Allows manually triggering the workflow
    inputs:
      target_environment:
        description: "Target Environment"
        required: true
        default: "demo"
env:
  KEYCLOAK_HOSTNAME_URL: "https://kc.zedwerks.com"
  DO_SPACES_URL: "https://zedwerks-terraform-s3.tor1.digitaloceanspaces.com"
  KEYCLOAK_TARGET_REALM: "smart"
  KEYCLOAK_TERRAFORM_CLIENT_ID: "terraform"
  TF_VAR_keycloak_terraform_client_secret: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}
  TF_VAR_keycloak_realm: "smart"
  TF_VAR_keycloak_terraform_client_id: "terraform"
  TF_VAR_keycloak_base_url: "https://kc.zedwerks.com"
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Override Backend Configuration"
        working-directory: ./example/terraform
        env:
          ENVIRONMENT: ${{ inputs.target_environment }}
        run: |
          rm -f backend.tf || true
          cp environments/$ENVIRONMENT/backend.tf backend.tf

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5 # Use your required Terraform version

      - name: "Terraform Init"
        working-directory: ./example/terraform
        env:
          ENVIRONMENT: ${{ inputs.target_environment }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
        run: |
          terraform init \
            --upgrade \
            -var-file=environments/$ENVIRONMENT/terraform.tfvars

      - name: "Terraform Imports"
        working-directory: ./example/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          KEYCLOAK_HOSTNAME_URL: "https://kc.zedwerks.com"
          KEYCLOAK_TARGET_REALM: "smart"
          KEYCLOAK_TERRAFORM_CLIENT_ID: "terraform"
          KEYCLOAK_TERRAFORM_CLIENT_SECRET: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}
          ENVIRONMENT: ${{ inputs.target_environment }}
        run: |
          printenv | grep KEYCLOAK
          bash ./scripts/tfimports.sh -var-file ./environments/$ENVIRONMENT/variables.tfvars

      - name: "Terraform Plan"
        working-directory: ./example/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          ENVIRONMENT: ${{ inputs.target_environment }}
        run: |
          terraform plan \
            -var-file=environments/$ENVIRONMENT/variables.tfvars

      - name: "Terraform Apply"
        working-directory: ./example/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          ENVIRONMENT: ${{ inputs.target_environment }}
        run: |
          terraform apply -auto-approve
            -var-file=environments/$ENVIRONMENT/variables.tfvars
